### ISSUE TITLE
unable to select from already uploaded icons

### ISSUE THREAD

**Issue by HeikoNardmann** [jenkinsci/custom-folder-icon-plugin#158]
### What feature do you want to see added?

After uploading a custom icon from my disk the icon for the current folder gets set. But what if I want to use the same icon again for some other folder? I don't see a way to browse and select an already uploaded icon?

Or am I missing something?

**Comment by strangelookingnerd** [comment]
@HeikoNardmann Thanks for your suggestion!

Currently this would only be possible by uploading the image again for each folder. I see that this can become a bit cumbersome when you have a larger number of folders. However an „image gallery“ is not something that would already be included in Jenkins UI libs so I need to figure something out and see if it is doable or feasible.

**Comment by strangelookingnerd** [comment]
Issue resolved and released with `2.6`

**Comment by HeikoNardmann** [comment]
Hey, I didn't expect this improvement within the next half year!!! Great! :smiley:
Hopefully I'll find time on Friday to try this.
Thanks a lot!

**Comment by HeikoNardmann** [comment]
Today I've updated the update information. Now the new version is listed. One problem: you now state that Jenkins 2.397 is the minimum. Is this high version number really required? I just have the 2.375.4 LTS and therefore are unable to install this update.
