### ISSUE TITLE
Custom logo not propagated to child of organisation folder

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/custom-folder-icon-plugin#387]
### Jenkins and plugins versions report

All. Latest versions

### What Operating System are you using (both controller, and any agents involved in the problem)?

All. Latest versions

### Reproduction steps

- Create organisation folder (Bitbucket, GitHub, etc)
- Configure a custom logo 
- Check that folders (multibranch) inside the organisation don't have the custom logo

I'm not sure if it's something that need fix on custom-folder-icon, branch-api or even Jenkins core ?

![backstage_icon_folder](https://github.com/user-attachments/assets/75cd1b02-93b4-4e2a-ac54-5b27869a1623)

### Expected Results

For organisation folder the custom logo is propagated to child multibranch pipelines folder

### Actual Results

![backstage_icon_folder2](https://github.com/user-attachments/assets/ea95d7a4-122f-4a67-bdd6-cb8cb2908839)

**Comment by strangelookingnerd** [comment]
From what I know there is no "inheritance" and each branch has its own icon. Compare it to nested folders if you will, the configuration is only on top-level. So not really a bug, but an interessting feature idea.

I guess this would need to be adapted in the branch-api. I can look into it a little deeper and let you know.

**Comment by strangelookingnerd** [comment]
Quick update:

If I followed it correctly the icon for a `ComputedFolder` such as Organization Folders (not sure if there are other implementations) is determined via [branch-api-plugin](https://github.com/jenkinsci/branch-api-plugin/blob/b4227cdbd5a2903adc7d5e3c7f2d67a690853392/src/main/java/jenkins/branch/OrganizationFolder.java#L565). 

The definition of the icon is up to the `SCMNavigator` implementations, such as [github-branch-source-plugin](https://github.com/jenkinsci/github-branch-source-plugin/blob/4ed4bdfc4a6a83384d2f521b666cdc59d3428c45/src/main/java/org/jenkinsci/plugins/github_branch_source/GitHubSCMNavigator.java#L1733).

Looking closer at the `SCMNavigator` implementation in [scm-api-plugin](https://github.com/jenkinsci/scm-api-plugin/blob/778d637ba7625f4dae8fe2ceb0e0aa5b429b9a02/src/main/java/jenkins/scm/api/SCMNavigator.java#L58) I see that - unfortunately - these are not `AbstractFolder` so my plugin can't provide the functionallity to have a custom icon.

So with that information, what are the options? I think it would be possible to propagate the icon for the children of a `ComputedFolder`. However this may not be really what the user wants / expects to have: the _same_ icon for everything.

Another option would be to make the icon of  `SCMNavigator` configurable and further have a plugin / extend this plugin (not sure if this is a great idea...) to provide the icons. 
Ultimately it would also be a solution to combine [custom-job-icon-plugin](https://github.com/jenkinsci/custom-job-icon-plugin) and custom-folder-icon-plugin to become the _custom-icon-for-everything-plugin_. 

What do you think @jonesbusy?

**Comment by jonesbusy** [comment]
Hi,

Thanks for all those details. I though it would be more easy that that. I'm not sure what would be the best solution to be honnest

Perhaps I will see if the "old" git icon can be replaced by one provided by ionicon (either git or the scm one). The actual one is very hugly and doesn't match all the rest of UI

I was also not aware of this (abandoned) plugin : https://plugins.jenkins.io/custom-job-icon/

Perhaps it could be adopted, refreshed and extended similar to the `custom-folder-icon-plugin`

**Comment by strangelookingnerd** [comment]
Closing here for now as the solution must likely be implemented elsewhere.

**Comment by jonesbusy** [comment]
Did some quick test on https://github.com/jenkinsci/custom-job-icon-plugin/pull/5 with only deps refresh

Surprisingly it's still able to display icons

If times permits I might adopt it and refresh it but I'm not sure if probably better a new plugin that directly implement https://github.com/jenkinsci/jenkins/pull/9723
