### ISSUE TITLE
Custom Icon implementation using ionicons-api-plugin

### ISSUE THREAD

**Issue by strangelookingnerd** [jenkinsci/custom-folder-icon-plugin#84]
### What feature do you want to see added?

The [ionicons-api-plugin](https://github.com/jenkinsci/ionicons-api-plugin) provides a collection of `svg` icons that could be used as a pool of existing icons for this plugin.

**Comment by jonesbusy** [comment]
Hi!

Thanks for the amazing job!

I found a small issue when using different theme. It looks like the ionicon color is not changed (like other icon of jenkins).

I opened a bug here : https://github.com/jenkinsci/custom-folder-icon-plugin/issues/93

Thanks
